# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.runs/synth_1/TOP_test_fft.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-fbvb900-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.cache/wt [current_project]
set_property parent.project_path C:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/kccistc/AppData/Roaming/Xilinx/Vivado/2020.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part avnet.com:ultrazed_7ev_cc:part0:1.5 [current_project]
set_property ip_output_repo c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/cos_rom_re.mem
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/cos_rom_im.mem
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/add_sub.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/add_sub_1_0_fac_8_0.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/add_sub_1_2.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/add_sub_2_0.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/add_sub_2_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/add_sub_2_2.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/add_sub_fac0.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/bit_shift.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/bit_shift_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly0.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly2.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_0_0.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_0_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_0_2.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_1_0.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_1_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_1_2.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_2_0.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_2_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/butterfly_2_2.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/cbfp.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/cbfp_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/cbfp_normalize.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/cos_gen_rom.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/delay.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/demux_1to2.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/fac8_1_1_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/fac_8_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/fac_8_1_2_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/fft_top.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/index_fifo.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/mag.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/mag_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/min.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/min_1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/mutl_tw.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/mux_2x1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/mux_twiddle_input.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/reorder.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/sat.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/shift_register.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/shift_register_1sub.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/twiddle_512.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/twiddle_64.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/twiddle_mult_m1.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/twiddle_mult_pipe.sv
  C:/Users/kccistc/Desktop/fft_pga/fft_vi/src/TOP_test_fft.sv
}
read_ip -quiet c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/vio_0/vio_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/kccistc/Desktop/fft_pga/fft_vi/constrs/uz7ev_evcc_factest.xdc
set_property used_in_implementation false [get_files C:/Users/kccistc/Desktop/fft_pga/fft_vi/constrs/uz7ev_evcc_factest.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top TOP_test_fft -part xczu7ev-fbvb900-1-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_test_fft.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_test_fft_utilization_synth.rpt -pb TOP_test_fft_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
