set_property SRC_FILE_INFO {cfile:C:/Users/kccistc/Desktop/fft_pga/fft_vi/constrs/uz7ev_evcc_factest.xdc rfile:../../../../../../../Users/kccistc/Desktop/fft_pga/fft_vi/constrs/uz7ev_evcc_factest.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC8 [get_ports clk_p]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC7 [get_ports clk_n]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports rstn]
