# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/D_drive_backup/Working/FPGA_AI_25_2/fft_fpga/fft_fpga.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
